@server = http://localhost:4004
@auth = Authorization: Basic alice:


### EmbeddingStorageService.DocumentChunks
GET {{server}}/odata/v4/embedding-storage/DocumentChunks
Content-Type: application/json
{{auth}}


### EmbeddingStorageService.DocumentChunks
POST {{server}}/odata/v4/embedding-storage/DocumentChunks
Content-Type: application/json
{{auth}}

{
  "ID": "1562500d-6cfd-4d99-b5b0-670f849b8821",
  "metadata": "metadata-1562500",
  "text_chunks": "text_chunks-1562500",
  "createdAt": "2010-07-30T23:00:00.000Z",
  "createdBy": "createdBy.xhms@example.com",
  "modifiedAt": "2008-01-12T23:00:00.000Z",
  "modifiedBy": "modifiedBy.xhms@example.com"
}


### EmbeddingStorageService.DocumentChunks
PATCH {{server}}/odata/v4/embedding-storage/DocumentChunks/1562500d-6cfd-4d99-b5b0-670f849b8821
Content-Type: application/json
{{auth}}

{
  "ID": "1562500d-6cfd-4d99-b5b0-670f849b8821",
  "metadata": "metadata-1562500",
  "text_chunks": "text_chunks-1562500",
  "createdAt": "2010-07-30T23:00:00.000Z",
  "createdBy": "createdBy.xhms@example.com",
  "modifiedAt": "2008-01-12T23:00:00.000Z",
  "modifiedBy": "modifiedBy.xhms@example.com"
}


### EmbeddingStorageService.DocumentChunks
DELETE {{server}}/odata/v4/embedding-storage/DocumentChunks/1562500d-6cfd-4d99-b5b0-670f849b8821
Content-Type: application/json
{{auth}}
