@server = http://localhost:4004
@auth = Authorization: Basic alice:


### JobPostingServie.DocumentChunks
GET {{server}}/odata/v4/job-posting-servie/DocumentChunks
Content-Type: application/json
{{auth}}


### JobPostingServie.DocumentChunks
POST {{server}}/odata/v4/job-posting-servie/DocumentChunks
Content-Type: application/json
{{auth}}

{
  "ID": "8602600e-5290-402b-8365-a6a3b78b2cd4",
  "metadata": "metadata-8602600",
  "text_chunks": "text_chunks-8602600",
  "createdAt": "2005-01-22T23:00:00.000Z",
  "createdBy": "createdBy.54dt4@example.net",
  "modifiedAt": "2000-07-09T23:00:00.000Z",
  "modifiedBy": "modifiedBy.54dt4@example.org"
}


### JobPostingServie.DocumentChunks
PATCH {{server}}/odata/v4/job-posting-servie/DocumentChunks/8602600e-5290-402b-8365-a6a3b78b2cd4
Content-Type: application/json
{{auth}}

{
  "ID": "8602600e-5290-402b-8365-a6a3b78b2cd4",
  "metadata": "metadata-8602600",
  "text_chunks": "text_chunks-8602600",
  "createdAt": "2005-01-22T23:00:00.000Z",
  "createdBy": "createdBy.54dt4@example.net",
  "modifiedAt": "2000-07-09T23:00:00.000Z",
  "modifiedBy": "modifiedBy.54dt4@example.org"
}


### JobPostingServie.DocumentChunks
DELETE {{server}}/odata/v4/job-posting-servie/DocumentChunks/8602600e-5290-402b-8365-a6a3b78b2cd4
Content-Type: application/json
{{auth}}


### JobPostingServie.JobPostings
GET {{server}}/odata/v4/job-posting-servie/JobPostings
Content-Type: application/json
{{auth}}


### JobPostingServie.JobPostings
POST {{server}}/odata/v4/job-posting-servie/JobPostings
Content-Type: application/json
{{auth}}

{
  "ID": "24090550-5f0a-40a1-901f-108a241c6d0c",
  "user_query": "user_query-24090550",
  "rag_response": "rag_response-24090550",
  "createdAt": "2014-06-19T23:00:00.000Z",
  "createdBy": "createdBy.eccdy@example.net",
  "modifiedAt": "2009-11-02T23:00:00.000Z",
  "modifiedBy": "modifiedBy.eccdy@example.net"
}


### JobPostingServie.JobPostings
PATCH {{server}}/odata/v4/job-posting-servie/JobPostings/24090550-5f0a-40a1-901f-108a241c6d0c
Content-Type: application/json
{{auth}}

{
  "ID": "24090550-5f0a-40a1-901f-108a241c6d0c",
  "user_query": "user_query-24090550",
  "rag_response": "rag_response-24090550",
  "createdAt": "2014-06-19T23:00:00.000Z",
  "createdBy": "createdBy.eccdy@example.net",
  "modifiedAt": "2009-11-02T23:00:00.000Z",
  "modifiedBy": "modifiedBy.eccdy@example.net"
}


### JobPostingServie.JobPostings
DELETE {{server}}/odata/v4/job-posting-servie/JobPostings/24090550-5f0a-40a1-901f-108a241c6d0c
Content-Type: application/json
{{auth}}


### Create a Job Posting using the chat model
GET {{server}}/odata/v4/job-posting-service/orchestrateJobPostingCreation(user_query='Create a Job Posting for a JavaScript Developer')
Content-Type: application/json
{{auth}}